In [ ]:
#========================================数据预处理==============================================================

In [ ]:
"""
1.标准化：标准化的前提是特征值服从正态分布，标准化后，其转换成标准正态分布； 
 使得每个属性的所有数据聚集在0 附近，方差为1

##sklearn 的实现方式 x'= （x-均值）/标准差
## 有两种实现方式:直接通过scale函数进行转化; 使用StandarScaler类，
使用该类的好处在于可以保存训练集中的参数（均值，方差）直接使用其对象转换测试集数据
"""

In [2]:
from sklearn import preprocessing
import numpy as np

In [3]:
##使用scale 类直接进行转化
X = np.array([[1.,-1.,-2.],
              [2.,0.,0.],
              [0.,1.,-1.]])
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487, -1.22474487],
       [ 1.22474487,  0.        ,  1.22474487],
       [-1.22474487,  1.22474487,  0.        ]])

In [4]:
X_scaled.mean(axis=0) ###计算每一列的数据

array([0., 0., 0.])

In [5]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [6]:
###standardScaler 类
scaler = preprocessing.StandardScaler().fit(X)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
scaler.mean_

array([ 1.,  0., -1.])

In [11]:
scaler.var_

array([0.66666667, 0.66666667, 0.66666667])

In [12]:
scaler.transform(X)

array([[ 0.        , -1.22474487, -1.22474487],
       [ 1.22474487,  0.        ,  1.22474487],
       [-1.22474487,  1.22474487,  0.        ]])

In [14]:
"""
2.区间缩放或者归一化：将属性缩放到一个指定的最大值和最小值（通常是1-0）之间，可以通过preprocessing.MinxMaxScaler类来实现
实现为：x' = (x-Min)/(Max-Min)
"""

"\n2.区间缩放：将属性缩放到一个指定的最大值和最小值（通常是1-0）之间，可以通过preprocessing.MinxMaxScaler类来实现\n实现为：x' = (x-Min)/(Max-Min)\n"

In [15]:
X_train= np.array([[1.,-1.,-2.],
              [2.,0.,0.],
              [0.,1.,-1.]])

In [17]:
min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler.fit_transform(X_train)

array([[0.5, 0. , 0. ],
       [1. , 0.5, 1. ],
       [0. , 1. , 0.5]])

In [19]:
"""
3. 不要中心化稀疏数据，引入正则化：
    正则化的过程是将每个样本缩放到单位范数（每个样本的范数为1），
    其目的在于样本向量在点乘运算或其他核函数计算相似性时，拥有统一的标准
    参考链接：https://www.cnblogs.com/chaosimple/p/4153167.html
"""


'\n3. 不要中心化稀疏数据，引入正则化：\n    正则化的过程是将每个样本缩放到单位范数（每个样本的范数为1），\n    其目的在于样本向量在点乘运算或其他核函数计算相似性时，拥有统一的标准\n'

In [21]:
X = np.array([[1.,-1.,-2.],
              [2.,0.,0.],
              [0.,1.,-1.]])
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized

array([[ 0.40824829, -0.40824829, -0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [23]:
"""
导入 iris 数据, 做后面实验数据
"""
from sklearn.datasets import load_iris
iris = load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [24]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
"""
4. 定量特征二值化：特征二值化的核心在于设定一个阈值， 大于阈值的赋值为1， 小于等于阈值的赋值为0
"""
from sklearn.preprocessing import Binarizer
Binarizer(threshold=3).fit_transform(iris.data)

array([[1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],


In [ ]:
"""
5. 定性特征编码: 这里使用sklearn 的OneHotEncoder
"""

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
data_train = iris.target.reshape((-1,1))
model = OneHotEncoder(sparse=False)  
model.fit(data_train)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=False)

In [45]:
model.transform(data_train)  ####如果sparse 设置为True ，最后的结果需要用model.transform(data_train).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
"""
6. 缺失值计算:Imputer 类提供了估算缺失值的基本策略，使用缺失值所在的行/列中的平均值、中位数或者众数来填充
strategy: mean 平均值； 
"""

In [56]:
from sklearn.preprocessing import Imputer


In [66]:
train_data = np.array([[1, 2], [np.nan, 3], [7, 6]])
test_data =  np.array([[np.nan, 2], [6, np.nan], [7, 6]])

In [67]:
###strategy 为mean, axis 为0
imp = Imputer(missing_values='NaN',strategy='mean',axis=0)
imp.fit(train_data)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [68]:
imp.transform(test_data)

array([[4.        , 2.        ],
       [6.        , 3.66666667],
       [7.        , 6.        ]])

In [69]:
###验证，计算 axis 为0 即列 的均值
np.nanmean(imp_data,axis=0)  ###通过numpy 得到的 均值 即为模型的均值，填充到test_data中

array([4.        , 3.66666667])

In [ ]:
"""
7. 数据变换：多项式变换PolynomialFeatures, 对数变换等
"""

In [70]:
from sklearn.preprocessing import PolynomialFeatures

In [71]:
X = np.arange(6).reshape(3,2)

In [72]:
###PolynomialFeatures 默认为2维， 这里将（X1,X2) 转化成 (1, X_1, X_2, X_1^2, X_1X_2, X_2^2)
## 参数interaction_only  默认为false, 是否只需要正交项。
## 如果 设置为true, 这里的转换是（X1,X2) 转化成 (1, X_1, X_2,X_1X_2)
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [73]:
poly = PolynomialFeatures(degree=2,interaction_only=True)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])

In [74]:
"""
8. 自定义转换器：FunctionTransformer
"""
from numpy import log1p
from sklearn.preprocessing import FunctionTransformer
FunctionTransformer(log1p).fit_transform(iris.data)

array([[1.80828877, 1.5040774 , 0.87546874, 0.18232156],
       [1.77495235, 1.38629436, 0.87546874, 0.18232156],
       [1.74046617, 1.43508453, 0.83290912, 0.18232156],
       [1.7227666 , 1.41098697, 0.91629073, 0.18232156],
       [1.79175947, 1.5260563 , 0.87546874, 0.18232156],
       [1.85629799, 1.58923521, 0.99325177, 0.33647224],
       [1.7227666 , 1.48160454, 0.87546874, 0.26236426],
       [1.79175947, 1.48160454, 0.91629073, 0.18232156],
       [1.68639895, 1.36097655, 0.87546874, 0.18232156],
       [1.77495235, 1.41098697, 0.91629073, 0.09531018],
       [1.85629799, 1.54756251, 0.91629073, 0.18232156],
       [1.75785792, 1.48160454, 0.95551145, 0.18232156],
       [1.75785792, 1.38629436, 0.87546874, 0.09531018],
       [1.66770682, 1.38629436, 0.74193734, 0.09531018],
       [1.91692261, 1.60943791, 0.78845736, 0.18232156],
       [1.90210753, 1.68639895, 0.91629073, 0.33647224],
       [1.85629799, 1.58923521, 0.83290912, 0.33647224],
       [1.80828877, 1.5040774 ,

In [ ]:
#=====================================特征选择======================================================================

In [ ]:
"""
1.Filter: 方差选择法； 相关系数法；卡方检验；互信息法
"""

In [ ]:
"""
方差选择法：使用sklearn 中的VarianceThreshold
"""

In [75]:
from sklearn.feature_selection import VarianceThreshold
VarianceThreshold(threshold=3).fit_transform(iris.data) ##只保留了一列的特征

array([[1.4],
       [1.4],
       [1.3],
       [1.5],
       [1.4],
       [1.7],
       [1.4],
       [1.5],
       [1.4],
       [1.5],
       [1.5],
       [1.6],
       [1.4],
       [1.1],
       [1.2],
       [1.5],
       [1.3],
       [1.4],
       [1.7],
       [1.5],
       [1.7],
       [1.5],
       [1. ],
       [1.7],
       [1.9],
       [1.6],
       [1.6],
       [1.5],
       [1.4],
       [1.6],
       [1.6],
       [1.5],
       [1.5],
       [1.4],
       [1.5],
       [1.2],
       [1.3],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [1.3],
       [1.3],
       [1.6],
       [1.9],
       [1.4],
       [1.6],
       [1.4],
       [1.5],
       [1.4],
       [4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
      

In [76]:
"""
相关系数法：先要计算各个特征对目标值的相关系数以及相关系数的p值
用feature_selection 库的SelectKBest 类结合相关系数来选择特征
"""
from sklearn.feature_selection import SelectKBest

In [80]:
###输出结果为（score, p-value）,当噪音比较小的时候，相关性很强，p-value很低
from scipy.stats import pearsonr
size=300
x = np.random.normal(0,1,size)
print("Lower noise", pearsonr(x, x + np.random.normal(0, 1, size)))
print("Higher noise", pearsonr(x, x + np.random.normal(0, 10, size)))

Lower noise (0.6538711966537304, 5.626422851812266e-38)
Higher noise (-0.037955664785317346, 0.5125302408761676)


In [82]:
"""
卡方检验：
"""
from sklearn.feature_selection import chi2
X,y = iris.data, iris.target
X.shape

(150, 4)

In [83]:
X_new = SelectKBest(chi2, k=2).fit_transform(X,y)
X_new.shape

(150, 2)

In [86]:
"""
互信息和最大信息系数：
"""


'\n互信息和最大信息系数：\n'

In [ ]:
"""
递归特征消除法：sklearn 中的RFE来实现

"""

In [91]:
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
iris = load_iris()
x, y = iris.data, iris.target

svc = SVC(kernel="linear", C=1)
rfe = RFE(estimator=svc, n_features_to_select=2, step=1)
rfe.fit(x, y)
ranking = rfe.ranking_
ranking
# [3 2 1 1] 说明第三维度特征和第四维度特征排名前2



array([3, 2, 1, 1])

In [93]:
rfe.n_features_

2

In [89]:
# 采用逻辑回归
ref2 = RFE(estimator=LogisticRegression(), n_features_to_select=2).fit(iris.data, iris.target)
ref2.ranking_
# [3 1 2 1]  这里则选择认为第二维和第四维特征重要

array([3, 1, 2, 1])

In [ ]:
"""
Embedded: sklearn 使用SelectFromModel

"""

In [ ]:
"""
基于L1 的特征选择:常用可以用的模型有
"""

In [94]:
# --- 例子，这里用支持向量机了 ---
### 这里LinearSVC 里面的penatly 设置成了l1,SelectFromModel 对应的threshold 为1e-5
from sklearn.svm import LinearSVC
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectFromModel
iris = load_iris()
X, y = iris.data, iris.target
X.shape
# (150, 4)
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X,y)  # 这里的惩罚项是L1,别看做是11，这里L是小写
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X)
X_new.shape ##丢弃了一个特征

(150, 3)

In [ ]:
"""
基于树模型的特征选择：GBDT 和 RF
"""

In [96]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import GradientBoostingClassifier
 
#GBDT作为基模型的特征选择
X_new = SelectFromModel(GradientBoostingClassifier()).fit_transform(iris.data, iris.target)
X_new.shape

(150, 2)